// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /*static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

   static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoUq5KEw4D1QUaGiLA_ZmmH-z0uAUrL-o',
    appId: '1:703350309747:web:285ef0fa2b3d9f173dbb06',
    messagingSenderId: '703350309747',
    projectId: 'yusportsapp',
    authDomain: 'yusportsapp.firebaseapp.com',
    storageBucket: 'yusportsapp.appspot.com',
    measurementId: 'G-NKXQDJDP9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGubJdlgL0aeyziz6HKtKEuHJAw70Hx3w',
    appId: '1:703350309747:android:ad5c379f0c4ec6af3dbb06',
    messagingSenderId: '703350309747',
    projectId: 'yusportsapp',
    storageBucket: 'yusportsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfdy6-6GYJ3JtiseEciCXzHOfrBIb-BMk',
    appId: '1:703350309747:ios:d6443ef481d1fca33dbb06',
    messagingSenderId: '703350309747',
    projectId: 'yusportsapp',
    storageBucket: 'yusportsapp.appspot.com',
    iosBundleId: 'com.example.yusports',
  ); */
}
